/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0d0d12',
        'surface-dim': '#0a0a0e',
        'surface-bright': '#1a1a24',
        'surface-container-lowest': '#050507',
        'surface-container-low': '#121217',
        'surface-container': '#18181b',
        'surface-container-high': '#27272a',
        'surface-container-highest': '#3f3f46',
        'on-surface': '#f4f4f5',
        'on-surface-variant': '#a1a1aa',
        'inverse-surface': '#f4f4f5',
        'inverse-on-surface': '#27272a',
        outline: '#52525b',
        'outline-variant': '#3f3f46',
        'surface-tint': '#f59e0b',
        primary: '#f59e0b',
        'on-primary': '#18181b',
        'primary-container': '#d97706',
        'on-primary-container': '#fef3c7',
        'inverse-primary': '#b45309',
        secondary: '#3b82f6',
        'on-secondary': '#eff6ff',
        'secondary-container': '#2563eb',
        'on-secondary-container': '#dbeafe',
        tertiary: '#10b981',
        'on-tertiary': '#ecfdf5',
        'tertiary-container': '#059669',
        'on-tertiary-container': '#d1fae5',
        error: '#ef4444',
        'on-error': '#fef2f2',
        'error-container': '#dc2626',
        'on-error-container': '#fee2e2',
        'primary-fixed': '#fef3c7',
        'primary-fixed-dim': '#fde68a',
        'on-primary-fixed': '#78350f',
        'on-primary-fixed-variant': '#92400e',
        background: '#0d0d12',
        'on-background': '#f4f4f5',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
